"""add reminder settings and logs

Revision ID: 3a10421837ae
Revises: 4c18e219a820
Create Date: 2026-03-23 04:45:21.925632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3a10421837ae"
down_revision: Union[str, None] = "4c18e219a820"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminder_logs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reminder_type", sa.String(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "reminder_type", "local_date"),
    )
    op.add_column("users", sa.Column("timezone", sa.String(), nullable=False))
    op.add_column("users", sa.Column("reminders_enabled", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reminders_enabled")
    op.drop_column("users", "timezone")
    op.drop_table("reminder_logs")
    # ### end Alembic commands ###
