"""adding fields for quiz table

Revision ID: a0fa626d9411
Revises: c8b5d7791405
Create Date: 2026-04-08 21:29:48.097439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0fa626d9411'
down_revision: Union[str, None] = 'c8b5d7791405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('quizzes', sa.Column('next_review_at', sa.DateTime(), nullable=False))
    op.add_column('quizzes', sa.Column('review_step', sa.Integer(), nullable=False))
    op.add_column('quizzes', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('quizzes', sa.Column('awaiting_response', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'awaiting_response')
    op.drop_column('quizzes', 'is_active')
    op.drop_column('quizzes', 'review_step')
    op.drop_column('quizzes', 'next_review_at')
    op.drop_column('quizzes', 'created_at')
    # ### end Alembic commands ###
