"""make topics user-owned

Revision ID: b92288cce978
Revises: f53fc259d18f
Create Date: 2026-03-15 22:30:53.883058

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b92288cce978"
down_revision: Union[str, None] = "f53fc259d18f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("topics", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        "uq_topics_user_id_title", "topics", ["user_id", "title"]
    )
    op.create_foreign_key(
        "fk_topics_user_id_users", "topics", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_topics_user_id_users", "topics", type_="foreignkey")
    op.drop_constraint("uq_topics_user_id_title", "topics", type_="unique")
    op.drop_column("topics", "user_id")
    # ### end Alembic commands ###
