"""remove unique topic_id from goals

Revision ID: c8b5d7791405
Revises: 576649867d14
Create Date: 2026-04-07 16:28:51.668325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b5d7791405'
down_revision: Union[str, None] = '576649867d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('goals_topic_id_key', 'goals', type_='unique')
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint('goals_topic_id_key', 'goals', ['topic_id'])
    # ### end Alembic commands ###
